/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package administrador;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel Arriola
 */
public class Registrar extends javax.swing.JPanel {
Conexion conectar=new Conexion();
Connection ConectarDB=conectar.getConection();
PreparedStatement Insertar=null;


    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();

         
    
    }
    void Cliente(){
        
        String Insert="INSERT INTO Clientes(Nombre,Apellido,DPI)values(?,?,?)";
        try {
            Insertar=ConectarDB.prepareCall(Insert);
            Insertar.setString(1, txtNombre.getText());
            Insertar.setString(2, txtApellido.getText());
            Insertar.setString(3, txtDPI.getText());
            Insertar.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Datos Agregados Correctamente ");
           // Limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
    }
    public void TipoPago(){
        String Insert="INSERT INTO TipoPago(TipoPago)values(?)";
        String TipoPago=(String) jComboBox1.getSelectedItem();
        try {
            Insertar=ConectarDB.prepareCall(Insert);
            Insertar.setString(1,TipoPago);
            Insertar.executeUpdate();
           // JOptionPane.showMessageDialog(null, "Datos Agregados Correctamente ");
           // Limpiar();
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
    }
    public void Pago(){
        String insert="INSERT INTO Pago(Pago,Membresia,idTipoPago)values(?,?,?)";
       // String Pagos =txtPago.getText();
        //int Pago=Integer.parseInt(Pagos);
        //txtPago.setText(Pago);
        String menbresia=(String) jComboBox2.getSelectedItem();
        
        try {
            Insertar=ConectarDB.prepareCall(insert);
            Insertar.setString(1,txtPago.getText());
            Insertar.setString(2, menbresia);
            Insertar.setString(3, txtID.getText());
            Insertar.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Datos agregados Correctamente a Pago");
           // Limpiar();
        } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
        
    }
    public void Ingreso(){
        
        String agregar="INSERT INTO Ingresos(idClientes,idPago,FechaIngreso)values(?,?,?)";
        
        try {
            Insertar=ConectarDB.prepareCall(agregar);
            Insertar.setString(1, txtID.getText());
            Insertar.setString(2, txtID.getText());
            Insertar.setString(3, txtFecha.getText());
            Insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "CLIENTE INSERTADO CORRECTAMENTE");
            Limpiar();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
        
    }
    void imagen(JLabel label, String root){
    ImageIcon image=new ImageIcon(root);
    Icon icon=new ImageIcon(
    image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT)
    );
    label.setIcon(icon);
    this.repaint();
}
public void Limpiar(){
    txtNombre.setText("");
    txtApellido.setText("");
    txtDPI.setText("");
   jComboBox1.setSelectedIndex(0);
   txtPago.setText("");
   jComboBox2.setSelectedIndex(0);
   txtFecha.setText("");
   txtID.setText("");
   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDPI = new javax.swing.JTextField();
        txtPago = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(87, 222, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(87, 222, 192));
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNombre.setCaretColor(new java.awt.Color(51, 255, 204));
        txtNombre.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 310, 60));

        txtApellido.setBackground(new java.awt.Color(87, 222, 192));
        txtApellido.setForeground(new java.awt.Color(51, 51, 51));
        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APELLIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtApellido.setCaretColor(new java.awt.Color(51, 255, 204));
        txtApellido.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 310, 60));

        txtDPI.setBackground(new java.awt.Color(87, 222, 192));
        txtDPI.setForeground(new java.awt.Color(51, 51, 51));
        txtDPI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DPI", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtDPI.setCaretColor(new java.awt.Color(51, 255, 204));
        txtDPI.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPIActionPerformed(evt);
            }
        });
        jPanel1.add(txtDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 310, 60));

        txtPago.setBackground(new java.awt.Color(87, 222, 192));
        txtPago.setForeground(new java.awt.Color(51, 51, 51));
        txtPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtPago.setCaretColor(new java.awt.Color(51, 255, 204));
        txtPago.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });
        txtPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 310, 60));

        jComboBox1.setBackground(new java.awt.Color(87, 222, 192));
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Pago", "Efectivo", "Targeta Credito", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 310, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("INGRESE  DATOS DEL CLIENTE ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 370, 40));

        txtFecha.setBackground(new java.awt.Color(87, 222, 192));
        txtFecha.setForeground(new java.awt.Color(51, 51, 51));
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESE FECHA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtFecha.setCaretColor(new java.awt.Color(51, 255, 204));
        txtFecha.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 310, 60));

        jComboBox2.setBackground(new java.awt.Color(87, 222, 192));
        jComboBox2.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Menbresía", "PREMIUN", "VIP", " " }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENBRESÍA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 310, 70));

        txtID.setBackground(new java.awt.Color(87, 222, 192));
        txtID.setForeground(new java.awt.Color(51, 51, 51));
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txtID.setCaretColor(new java.awt.Color(51, 255, 204));
        txtID.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 310, 60));

        jButton1.setBackground(new java.awt.Color(87, 222, 192));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("REGISTRAR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 150, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPIActionPerformed

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cliente();
        TipoPago();
        Pago();
        Ingreso();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
        char Validar=evt.getKeyChar();
        if(Validar<'0'||Validar>'9') evt.consume();
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoKeyTyped
        // TODO add your handling code here:
        //solo acepta numeros 
        char Validar =evt.getKeyChar();
          if(Validar<'0'||Validar>'9') evt.consume();
    }//GEN-LAST:event_txtPagoKeyTyped

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
