/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package administrador;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel Arriola
 */
public class Registrar extends javax.swing.JPanel {
Conexion conectar=new Conexion();
Connection ConectarDB=conectar.getConection();
PreparedStatement Insertar=null;


    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();

         
     
      
    }
    void Cliente(){
        
        String Insert="INSERT INTO Clientes(Nombre,Apellido,DPI)values(?,?,?)";
        try {
            Insertar=ConectarDB.prepareCall(Insert);
            Insertar.setString(1, txtNombre.getText());
            Insertar.setString(2, txtApellido.getText());
            Insertar.setString(3, txtDPI.getText());
            Insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Agregados Correctamente ");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
    }
    public void TipoPago(){
        String Insert="INSERT INTO TipoPago(TipoPago)values(?)";
        String TipoPago=(String) jComboBox1.getSelectedItem();
        try {
            Insertar=ConectarDB.prepareCall(Insert);
            Insertar.setString(1,TipoPago);
            Insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Agregados Correctamente ");
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
    }
    public void Pago(){
        String insert="INSERT INTO Pago(Pago,Membresia,idTipoPago)values(?,?,?)";
       // String Pagos =txtPago.getText();
        //int Pago=Integer.parseInt(Pagos);
        //txtPago.setText(Pago);
        String menbresia=(String) jComboBox2.getSelectedItem();
        
        try {
            Insertar=ConectarDB.prepareCall(insert);
            Insertar.setString(1,txtPago.getText());
            Insertar.setString(2, menbresia);
            Insertar.setString(3, txtID.getText());
            Insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos agregados Correctamente a Pago");
        } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
        
    }
    public void Ingreso(){
        
        String agregar="INSERT INTO Ingresos(idClientes,idPago,FechaIngreso)values(?,?,?)";
        
        try {
            Insertar=ConectarDB.prepareCall(agregar);
            Insertar.setString(1, txtID.getText());
            Insertar.setString(2, txtID.getText());
            Insertar.setString(3, txtFecha.getText());
            Insertar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Agregados Correctamente a Ingresos");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Datos no  Agregados Correctamente "+e.toString());
        }
        
    }
    void imagen(JLabel label, String root){
    ImageIcon image=new ImageIcon(root);
    Icon icon=new ImageIcon(
    image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT)
    );
    label.setIcon(icon);
    this.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        txtDPI = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtPago = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        txtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(87, 222, 192));
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Nombre");
        txtNombre.setBorder(null);
        txtNombre.setCaretColor(new java.awt.Color(51, 255, 204));
        txtNombre.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 310, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 173, 310, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 310, 10));

        txtApellido.setBackground(new java.awt.Color(87, 222, 192));
        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("Apellido");
        txtApellido.setBorder(null);
        txtApellido.setCaretColor(new java.awt.Color(51, 255, 204));
        txtApellido.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 310, 30));

        txtDPI.setBackground(new java.awt.Color(87, 222, 192));
        txtDPI.setForeground(new java.awt.Color(153, 153, 153));
        txtDPI.setText("DPI");
        txtDPI.setBorder(null);
        txtDPI.setCaretColor(new java.awt.Color(51, 255, 204));
        txtDPI.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPIActionPerformed(evt);
            }
        });
        jPanel1.add(txtDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 310, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 310, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 310, 10));

        txtPago.setBackground(new java.awt.Color(87, 222, 192));
        txtPago.setForeground(new java.awt.Color(153, 153, 153));
        txtPago.setText("Pago");
        txtPago.setBorder(null);
        txtPago.setCaretColor(new java.awt.Color(51, 255, 204));
        txtPago.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPagoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 310, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 310, 10));

        jComboBox1.setBackground(new java.awt.Color(87, 222, 192));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo Pago", "Efectivo", "Targeta Credito", " " }));
        jComboBox1.setBorder(null);
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 310, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("INGRESE SUS DATOS ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 250, 40));

        txtFecha.setBackground(new java.awt.Color(87, 222, 192));
        txtFecha.setForeground(new java.awt.Color(153, 153, 153));
        txtFecha.setText("Fecha Ingreso");
        txtFecha.setBorder(null);
        txtFecha.setCaretColor(new java.awt.Color(51, 255, 204));
        txtFecha.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 310, 30));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 310, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 310, 10));

        jComboBox2.setBackground(new java.awt.Color(87, 222, 192));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menbresía", "PREMIUN", "VIP", " " }));
        jComboBox2.setBorder(null);
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 310, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 310, 10));

        txtID.setBackground(new java.awt.Color(87, 222, 192));
        txtID.setForeground(new java.awt.Color(153, 153, 153));
        txtID.setText("ID CLIENTE");
        txtID.setBorder(null);
        txtID.setCaretColor(new java.awt.Color(51, 255, 204));
        txtID.setSelectionColor(new java.awt.Color(51, 255, 204));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 310, 30));

        jButton1.setBackground(new java.awt.Color(87, 222, 192));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("REGISTRAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 150, 50));

        jLabel1.setBackground(new java.awt.Color(73, 192, 165));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Registro.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPIActionPerformed

    private void txtPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPagoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Cliente();
        TipoPago();
        Pago();
        Ingreso();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
